### ISSUE TITLE
Error loading input file

### ISSUE THREAD

**Issue by adRn-s** [mulinlab/CAUSALdb-finemapping-pip#7]
I got this message:

```
Traceback (most recent call last):
  File "fine_map_pipe.py", line 230, in <module>
    df = df.dropna(subset=['CHR','BP','EA','NEA','BETA','SE','P','Zscore'])
  File "/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py", line 5004, in dropna
    raise KeyError(list(np.compress(check, subset)))
KeyError: ['CHR', 'BP', 'EA', 'NEA', 'BETA', 'SE', 'P', 'Zscore']
```

What am I doing wrong?

Input data to reproduce error: https://transfer.sh/l01PM/causaldb_input.tsv

Thanks in advance.

**Comment by adRn-s** [comment]
Oh, I think is because I forgot to save hader.
