### ISSUE TITLE
Error: file not found (./causaldb_input/*)

### ISSUE THREAD

**Issue by adRn-s** [mulinlab/CAUSALdb-finemapping-pip#8]
```
loading input file
split files
prepare input files of finemapping tools
run finemapping tools
gather results

wc: /content/drive/MyDrive/egg19/CAUSALdb-finemapping-pip/causaldb_input/causaldb_input_2_46482634_47318772.processed.caviarbf: No such file or directory
wc: /content/drive/MyDrive/egg19/CAUSALdb-finemapping-pip/causaldb_input/causaldb_input_2_23341383_24686918.processed.caviarbf: No such file or directory
wc: /content/drive/MyDrive/egg19/CAUSALdb-finemapping-pip/causaldb_input/causaldb_input_4_17383322_18841874.processed.caviarbf: No such file or directory
wc: /content/drive/MyDrive/egg19/CAUSALdb-finemapping-pip/causaldb_input/causaldb_input_3_121974097_123517768.processed.caviarbf: No such file or directory
wc: /content/drive/MyDrive/egg19/CAUSALdb-finemapping-pip/causaldb_input/causaldb_input_2_167355970_169968236.processed.caviarbf: No such file or directory
wc: /content/drive/MyDrive/egg19/CAUSALdb-finemapping-pip/causaldb_input/causaldb_input_7_43159074_44763828.processed.caviarbf: No such file or directory
wc: /content/drive/MyDrive/egg19/CAUSALdb-finemapping-pip/causaldb_input/causaldb_input_6_151912703_153094496.processed.caviarbf: No such file or directory
wc: /content/drive/MyDrive/egg19/CAUSALdb-finemapping-pip/causaldb_input/causaldb_input_6_19207487_21684065.processed.caviarbf: No such file or directory
wc: /content/drive/MyDrive/egg19/CAUSALdb-finemapping-pip/causaldb_input/causaldb_input_3_156008700_157312028.processed.caviarbf: No such file or directory
wc: /content/drive/MyDrive/egg19/CAUSALdb-finemapping-pip/causaldb_input/causaldb_input_7_71874885_73334602.processed.caviarbf: No such file or directory
wc: /content/drive/MyDrive/egg19/CAUSALdb-finemapping-pip/causaldb_input/causaldb_input_8_40703337_41721454.processed.caviarbf: No such file or directory
wc: /content/drive/MyDrive/egg19/CAUSALdb-finemapping-pip/causaldb_input/causaldb_input_9_96671698_98922040.processed.caviarbf: No such file or directory
wc: /content/drive/MyDrive/egg19/CAUSALdb-finemapping-pip/causaldb_input/causaldb_input_14_99138532_101534307.processed.caviarbf: No such file or directory
wc: /content/drive/MyDrive/egg19/CAUSALdb-finemapping-pip/causaldb_input/causaldb_input_12_65559695_67181144.processed.caviarbf: No such file or directory
wc: /content/drive/MyDrive/egg19/CAUSALdb-finemapping-pip/causaldb_input/causaldb_input_10_93335047_95396368.processed.caviarbf: No such file or directory
wc: /content/drive/MyDrive/egg19/CAUSALdb-finemapping-pip/causaldb_input/causaldb_input_10_115328432_116421406.processed.caviarbfwc: /content/drive/MyDrive/egg19/CAUSALdb-finemapping-pip/causaldb_input/causaldb_input_11_1213590_3665481.processed.caviarbf: No such file or directorywc: : No such file or directory

/content/drive/MyDrive/egg19/CAUSALdb-finemapping-pip/causaldb_input/causaldb_input_15_38530777_40384132.processed.caviarbf: No such file or directory
wc: /content/drive/MyDrive/egg19/CAUSALdb-finemapping-pip/causaldb_input/causaldb_input_15_96141596_98030910.processed.caviarbf: No such file or directory
wc: /content/drive/MyDrive/egg19/CAUSALdb-finemapping-pip/causaldb_input/causaldb_input_15_98030910_99244059.processed.caviarbf: No such file or directory
wc: /content/drive/MyDrive/egg19/CAUSALdb-finemapping-pip/causaldb_input/causaldb_input_20_22491456_23293790.processed.caviarbf: No such file or directory
wc: /content/drive/MyDrive/egg19/CAUSALdb-finemapping-pip/causaldb_input/causaldb_input_17_5741334_7317398.processed.caviarbf: No such file or directory
wc: /content/drive/MyDrive/egg19/CAUSALdb-finemapping-pip/causaldb_input/causaldb_input_20_25344231_31614823.processed.caviarbf: No such file or directory
wc: /content/drive/MyDrive/egg19/CAUSALdb-finemapping-pip/causaldb_input/causaldb_input_20_38436761_39610856.processed.caviarbf: No such file or directory
wc: /content/drive/MyDrive/egg19/CAUSALdb-finemapping-pip/causaldb_input/causaldb_input_22_27834752_29651799.processed.caviarbf: No such file or directory
Traceback (most recent call last):
  File "fine_map_pipe.py", line 286, in <module>
    get_credible_set(prefix)
  File "fine_map_pipe.py", line 130, in get_credible_set
    df = pd.read_csv(f'{out_dir}/{meta_id}_{chr_id}_{start}_{stop}.causal.txt',sep='\t',names=names)
  File "/usr/local/lib/python3.7/dist-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.7/dist-packages/pandas/io/parsers.py", line 454, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/usr/local/lib/python3.7/dist-packages/pandas/io/parsers.py", line 948, in __init__
    self._make_engine(self.engine)
  File "/usr/local/lib/python3.7/dist-packages/pandas/io/parsers.py", line 1180, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/usr/local/lib/python3.7/dist-packages/pandas/io/parsers.py", line 2010, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/egg19/CAUSALdb-finemapping-pip/causaldb_input/causaldb_input_2_23341383_24686918.causal.txt'
```

There's a bunch of files at `./causaldb_input/*` but not that one.

Input data to reproduce error: https://transfer.sh/l01PM/causaldb_input.tsv

**Comment by adRn-s** [comment]
Please note that the input data I'm sharing lacks the header: `['CHR', 'BP', 'rsID', 'MAF', 'EA', 'NEA', 'BETA', 'SE', 'P', 'Zscore']` I've added it manually after upload. Sorry for the slight inconvenience.

**Comment by adRn-s** [comment]
It might be the problem is from upstream software, `caviarbf`.

**Comment by vermaa1** [comment]
I am getting the same error. Did you find a solution to resolve this issue? @Jianhua-Wang, do you have any suggestions to resolve this issue?

**Comment by vermaa1** [comment]
After further testing, I found that the issue is with errors in the fine-mapping tools. None of them are processing the files and generating the output. I commented out the STDOUT part and here is what the output looks like:

```

loading input file /git/CAUSALdb-finemapping-pip/GR018
split files
prepare input files of finemapping tools
run finemapping tools
Reading in files for: GR018_1_54226262_56413117.processed
Reading in files for: GR018_1_108409665_110303931.processed
Reading in files for: GR018_1_56413117_57021728.processed
Running PAINTOR with full enumeration of a maximum of 1 causals per locus
Assertion failed: (row >= 0 && row < rows() && col >= 0 && col < cols()), function operator(), file //git/CAUSALdb-finemapping-pip/bin/PAINTOR_V3.0-3.0/eigen/Eigen/src/Core/DenseCoeffsBase.h, line 337.
Running PAINTOR with full enumeration of a maximum of 1 causals per locus
Assertion failed: (row >= 0 && row < rows() && col >= 0 && col < cols()), function operator(), file //git/CAUSALdb-finemapping-pip/bin/PAINTOR_V3.0-3.0/eigen/Eigen/src/Core/DenseCoeffsBase.h, line 337.
Running PAINTOR with full enumeration of a maximum of 1 causals per locus
Assertion failed: (row >= 0 && row < rows() && col >= 0 && col < cols()), function operator(), file //git/CAUSALdb-finemapping-pip/bin/PAINTOR_V3.0-3.0/eigen/Eigen/src/Core/DenseCoeffsBase.h, line 337.
Reading in files for: GR018_2_233550003_235150987.processed
Running PAINTOR with full enumeration of a maximum of 1 causals per locus
Assertion failed: (row >= 0 && row < rows() && col >= 0 && col < cols()), function operator(), file //git/CAUSALdb-finemapping-pip/bin/PAINTOR_V3.0-3.0/eigen/Eigen/src/Core/DenseCoeffsBase.h, line 337.
Reading in files for: GR018_2_43309590_44313803.processed
Running PAINTOR with full enumeration of a maximum of 1 causals per locus
Assertion failed: (row >= 0 && row < rows() && col >= 0 && col < cols()), function operator(), file //git/CAUSALdb-finemapping-pip/bin/PAINTOR_V3.0-3.0/eigen/Eigen/src/Core/DenseCoeffsBase.h, line 337.
Assertion failed: (row >= 0 && row < rows() && col >= 0 && col < cols()), function operator(), file ../eigen-eigen-1306d75b4a21/Eigen/src/Core/DenseCoeffsBase.h, line 337.
Assertion failed: (row >= 0 && row < rows() && col >= 0 && col < cols()), function operator(), file ../eigen-eigen-1306d75b4a21/Eigen/src/Core/DenseCoeffsBase.h, line 337.
Reading in files for: GR018_1_222230220_224938520.processed
Reading in files for: GR018_3_137371083_139954597.processed
Reading in files for: GR018_2_215573795_217715661.processed
Reading in files for: GR018_3_153256571_154714218.processed
Reading in files for: GR018_2_202818637_205799241.processed
Running PAINTOR with full enumeration of a maximum of 1 causals per locus
Assertion failed: (row >= 0 && row < rows() && col >= 0 && col < cols()), function operator(), file //git/CAUSALdb-finemapping-pip/bin/PAINTOR_V3.0-3.0/eigen/Eigen/src/Core/DenseCoeffsBase.h, line 337.
Running PAINTOR with full enumeration of a maximum of 1 causals per locus
Assertion failed: (row >= 0 && row < rows() && col >= 0 && col < cols()), function operator(), file //git/CAUSALdb-finemapping-pip/bin/PAINTOR_V3.0-3.0/eigen/Eigen/src/Core/DenseCoeffsBase.h, line 337.
Running PAINTOR with full enumeration of a maximum of 1 causals per locus
Assertion failed: (row >= 0 && row < rows() && col >= 0 && col < cols()), function operator(), file //git/CAUSALdb-finemapping-pip/bin/PAINTOR_V3.0-3.0/eigen/Eigen/src/Core/DenseCoeffsBase.h, line 337.
Running PAINTOR with full enumeration of a maximum of 1 causals per locus
Running PAINTOR with full enumeration of a maximum of 1 causals per locus
Assertion failed: (row >= 0 && row < rows() && col >= 0 && col < cols()), function operator(), file //git/CAUSALdb-finemapping-pip/bin/PAINTOR_V3.0-3.0/eigen/Eigen/src/Core/DenseCoeffsBase.h, line 337.
Assertion failed: (row >= 0 && row < rows() && col >= 0 && col < cols()), function operator(), file //git/CAUSALdbAssertion failed: (row >= 0 && r-finemapping-pip/bin/PAINTOR_V3.0-3.0/eigen/Eigen/src/Core/DenseCoeffsBase.h, line 337.
ow < rows() && col >= 0 && col < cols()), function operator(), file ../eigen-eigen-1306d75b4a21/Eigen/src/Core/DenseCoeffsBase.h, line 337.
Assertion failed: (row >= 0 && row < rows() && col >= 0 && col < cols()), function operator(), file ../eigen-eigen-1306d75b4a21/Eigen/src/Core/DenseCoeffsBase.h, line 337.
reading file: /git/CAUSALdb-finemapping-pip/GR018/GR018_1_56413117_57021728.processed.caviarbf.out
reading file: /git/CAUSALdb-finemapping-pip/GR018/GR018_1_108409665_110303931.processed.caviarbf.out
/git/CAUSALdb-finemapping-pip/GR018/GR018_1_56413117_57021728.processed.caviarbf.out: line number is not correct
/git/CAUSALdb-finemapping-pip/GR018/GR018_1_108409665_110303931.processed.caviarbf.out: line number is not correct
reading file: /git/CAUSALdb-finemapping-pip/GR018/GR018_2_233550003_235150987.processed.caviarbf.out
/git/CAUSALdb-finemapping-pip/GR018/GR018_2_233550003_235150987.processed.caviarbf.out: line number is not correct
Assertion failed: (row >= 0 && row < rows() && col >= reading file: /git/CAUSALdb-finemapping-pip/GR018/GR018_2_43309590_44313803.processed.caviarbf.out
Assertion failed: (row >= 0 && row < rows() && col >= 0 && col < cols()), function operator(), file ../eigen-eigen-1306d75b4a21/Eigen/src/Core/DenseCoeffsBase.h, line 337.
Assertion failed: (row >= 0 && row < rows() && col >= 0 && col < cols()), function operator(), file ../eigen-eigen-1306d75b4a21/Eigen/src/Core/DenseCoeffsBase.hAssertion failed: (row >= 0 && r, line 337.
ow < rows() && col >= 0 && col < cols()), function operator(), file ../eigen-eigen-1306d75b4a21/Eigen/src/Core/DenseCoeffsBase.h, line 337.
Assertion failed: (row >= 0 && row < rows() && col >= 0 && col < cols()), function operator(), file ../eigen-eigen-1306d75b4a21/Eigen/src/Core/DenseCoeffsBase.h, line 337.
0 && col < cols()), function operator(), file ../eigen-eigen-1306d75b4a21/Eigen/src/Core/DenseCoeffsBase.h, line 337.
/git/CAUSALdb-finemapping-pip/GR018/GR018_2_43309590_44313803.processed.caviarbf.out: line number is not correct
Assertion failed: (row >= 0 && row < rows() && col >= 0 && col < cols()), function operator(), file ../eigen-eigen-1306d75b4a21/Eigen/src/Core/DenseCoeffsBase.h, line 337.

|--------------------------------------|
| Welcome to FINEMAP v1.3.1            |
|                                      |
| (c) 2015-2018 University of Helsinki |
|                                      |
| Help :                               |
| - ./finemap --help                   |
| - www.finemap.me                     |
| - www.christianbenner.com            |
|                                      |
| Contact :                            |
| - christian.benner@helsinki.fi       |
| - matti.pirinen@helsinki.fi          |
|--------------------------------------|

--------
SETTINGS
--------
- dataset         : all
- corr-config     : 0.95
- n-causal-snps   : 1
- n-configs-top   : 50000
- n-convergence   : 1000
- n-iterations    : 100000
- prior-k0        : 0
- prior-std       : 0.05 
- prob-tol        : 0.001


|--------------------------------------|
| Welcome to FINEMAP v1.3.1            |
|                                      |
| (c) 2015-2018 University of Helsinki |
|                                      |
| Help :                               |
| - ./finemap --help                   |
| - www.finemap.me                     |
| - www.christianbenner.com            |
|                                      |
| Contact :                            |
| - christian.benner@helsinki.fi       |
| - matti.pirinen@helsinki.fi          |
|--------------------------------------|


|--------------------------------------|
| Welcome to FINEMAP v1.3.1            |
|                                      |
| (c) 2015-2018 University of Helsinki |
|                                      |
| Help :                               |
| - ./finemap --help                   |
| - www.finemap.me                     |
| - www.christianbenner.com            |
|                                      |
| Contact :                            |
| - christian.benner@helsinki.fi       |
| - matti.pirinen@helsinki.fi          |
|--------------------------------------|

reading file: /git/CAUSALdb-finemapping-pip/GR018/GR018_2_215573795_217715661.processed.caviarbf.out
/git/CAUSALdb-finemapping-pip/GR018/GR018_2_215573795_217715661.processed.caviarbf.out: line number is not correct
------------
FINE-MAPPING (1/1)
------------
- GWAS summary stats               : /git/CAUSALdb-finemapping-pip/GR018/GR018_1_108409665_110303931.processed.z
--------
- SNP correlations                 : /git/CAUSALdb-finemapping-pip/GR018/GR018_1_108409665_110303931.processed.ld
SETTINGS
--------
- Causal SNP stats                 : /git/CAUSALdb-finemapping-pip/GR018/GR018_1_108409665_110303931.processed.snp
- dataset         : all
- Causal configurations            : /git/CAUSALdb-finemapping-pip/GR018/GR018_1_108409665_110303931.processed.config
- Credible sets                    : /git/CAUSALdb-finemapping-pip/GR018/GR018_1_108409665_110303931.processed.cred
reading file: /git/CAUSALdb-finemapping-pip/GR018/GR018_3_137371083_139954597.processed.caviarbf.out
- corr-config     : 0.95
- n-causal-snps   : 1
- n-configs-top   : 50000
- n-convergence   : 1000
- n-iterations    : 100000
- prior-k0        : 0
- prior-std       : 0.05 
- prob-tol        : 0.001



Error : File '/git/CAUSALdb-finemapping-pip/GR018/GR018_1_108409665_110303931.processed.z' contains only 1 SNP!

gather results
Traceback (most recent call last):
  File "fine_map_pipe.py", line 287, in <module>
    get_credible_set(prefix)
  File "fine_map_pipe.py", line 130, in get_credible_set
    df = pd.read_csv(f'{out_dir}/{meta_id}_{chr_id}_{start}_{stop}.causal.txt',sep='\t',names=names)
  File "/anaconda3/envs/finemap/lib/python3.6/site-packages/pandas/io/parsers.py", line 705, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/anaconda3/envs/finemap/lib/python3.6/site-packages/pandas/io/parsers.py", line 445, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/anaconda3/envs/finemap/lib/python3.6/site-packages/pandas/io/parsers.py", line 814, in __init__
    self._make_engine(self.engine)
  File "/anaconda3/envs/finemap/lib/python3.6/site-packages/pandas/io/parsers.py", line 1045, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/anaconda3/envs/finemap/lib/python3.6/site-packages/pandas/io/parsers.py", line 1684, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 391, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 710, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: File b'/git/CAUSALdb-finemapping-pip/GR018/GR018_1_54226262_56413117.causal.txt' does not exist

```

```

**Comment by silvenchu** [comment]
Hello, I would like to know if the previous issue from @vermaa1 was solved, I am finding the same error with the example input:

"FileNotFoundError: File b'/git/CAUSALdb-finemapping-pip/GR018/GR018_1_54226262_56413117.causal.txt' does not exist"

In addition, I have experiencing problems activating finemap. After running "conda activate finemap" I get this:

"Could not find conda environment: finemap"

I checked and I have conda 4.8.2 installed and "finemapcondaenv.yml" is in /CAUSALdb-finemapping-pip/bin/ directory.

Could you help please?

**Comment by Jianhua-Wang** [comment]
@silvenchu I updated the environment yml file and tested with conda 4.10. Please try with the updated files.

**Comment by silvenchu** [comment]
Hello Jianhua,

Thank you very much for your response!

Yes, I activate the environment. My version of conda is 4.11. These are my
commands using the latest version of the environment:

conda env create -f
/home/lab022/WORK/Silvia/credset/CAUSALdb-finemapping-pip/bin/finemapcondaenv.yml

conda activate finemap

python3 fine_map_pipe.py -s 120575 ./input/GR018.txt.gz output

After running the third command I got the following error:

loading input file
split files
prepare input files of finemapping tools
run finemapping tools
gather results
Traceback (most recent call last):
  File "fine_map_pipe.py", line 286, in <module>
    get_credible_set(prefix)
  File "fine_map_pipe.py", line 130, in get_credible_set
    df =
pd.read_csv(f'{out_dir}/{meta_id}_{chr_id}_{start}_{stop}.causal.txt',sep='\t',names=names)
  File
"/home/lab022/anaconda3/envs/finemap/lib/python3.6/site-packages/pandas/io/parsers.py",
line 705, in parser_f
    return _read(filepath_or_buffer, kwds)
  File
"/home/lab022/anaconda3/envs/finemap/lib/python3.6/site-packages/pandas/io/parsers.py",
line 445, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File
"/home/lab022/anaconda3/envs/finemap/lib/python3.6/site-packages/pandas/io/parsers.py",
line 814, in __init__
    self._make_engine(self.engine)
  File
"/home/lab022/anaconda3/envs/finemap/lib/python3.6/site-packages/pandas/io/parsers.py",
line 1045, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File
"/home/lab022/anaconda3/envs/finemap/lib/python3.6/site-packages/pandas/io/parsers.py",
line 1684, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 391, in
pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 710, in
pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: File
b'/home/lab022/WORK/Silvia/credset/CAUSALdb-finemapping-pip/GR018/GR018_1_54226262_56413117.causal.txt'
does not exist

This is how the input file looks like:
(finemap) ***@***.***:~/WORK/Silvia/credset/CAUSALdb-finemapping-pip/input$
head GR018.txt                              CHR     BP      rsID    MAF
EA      NEA  BETA       SE      P       Zscore
1       762320  exm2268640              C    T  -2.1671804559878427
2.2192489884814903      0.3288  -0.9765377689642318
1       865584  exm44           G       A    -0.7989522394569218
 0.9458814406017895      0.3983  -0.844664251947487
1       865625  exm46           G       A    -1.723727058836228
1.3810903732349589      0.212   -1.2480914299610266
1       865628  exm47           A       G    -3.798694320121143
11.010921607693835      0.7301  -0.34499331259127497
1       865662  exm51           G       A    -1.6841614586300369
 1.0159911755963904      0.09739 -1.657653628380609
1       865665  exm53           G       A    -2.0091694886945044
 2.640410901770726       0.4467  -0.7609306139991715
1       865694  exm55           C       T    -1.0624732420522365
 0.4776340446018991      0.02612 -2.2244504010131694
1       866438  exm63           G       A    -0.8360941898798784
 1.1243371703006841      0.4571  -0.7436329705761482
1       874501  exm94           C       T    -2.6664285264113907
 8.142085007626491       0.7433  -0.32748718834473145

Do you know what can be going wrong? Thanks a lot!!

Silvia
