### ISSUE TITLE
File Not Found error: File (...) /.causal.txt' does not exist"

### ISSUE THREAD

**Issue by silvenchu** [mulinlab/CAUSALdb-finemapping-pip#9]
Hello, 

I'm running the code using the example input GR018. I cloned the repo, set up conda environment and download fine-mapping tools and build the reference panel without errors. However, after running:

python fine_map_pipe.py -s 120575 ./input/GR018.txt.gz output

I foun the following error:

"FileNotFoundError: File b'/git/CAUSALdb-finemapping-pip/GR018/GR018_1_54226262_56413117.causal.txt' does not exist"

Could you help please?

**Comment by Jianhua-Wang** [comment]
Did you activate the conda environment before you ran the command?

**Comment by silvenchu** [comment]
Hello Jianhua,

Thank you very much for your response! 

Yes, I activate the environment. My version of conda is 4.11. These are my commands using the latest version of the environment:

conda env create -f /home/lab022/WORK/Silvia/credset/CAUSALdb-finemapping-pip/bin/finemapcondaenv.yml

conda activate finemap

python3 fine_map_pipe.py -s 120575 ./input/GR018.txt.gz output

After running the third command I got the following error:

loading input file
split files
prepare input files of finemapping tools
run finemapping tools
gather results
Traceback (most recent call last):
  File "fine_map_pipe.py", line 286, in <module>
    get_credible_set(prefix)
  File "fine_map_pipe.py", line 130, in get_credible_set
    df = pd.read_csv(f'{out_dir}/{meta_id}_{chr_id}_{start}_{stop}.causal.txt',sep='\t',names=names)
  File "/home/lab022/anaconda3/envs/finemap/lib/python3.6/site-packages/pandas/io/parsers.py", line 705, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/lab022/anaconda3/envs/finemap/lib/python3.6/site-packages/pandas/io/parsers.py", line 445, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/lab022/anaconda3/envs/finemap/lib/python3.6/site-packages/pandas/io/parsers.py", line 814, in __init__
    self._make_engine(self.engine)
  File "/home/lab022/anaconda3/envs/finemap/lib/python3.6/site-packages/pandas/io/parsers.py", line 1045, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/lab022/anaconda3/envs/finemap/lib/python3.6/site-packages/pandas/io/parsers.py", line 1684, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 391, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 710, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: File b'/home/lab022/WORK/Silvia/credset/CAUSALdb-finemapping-pip/GR018/GR018_1_54226262_56413117.causal.txt' does not exist

This is how the input file looks like:
(finemap) lab022@PCIR1184:~/WORK/Silvia/credset/CAUSALdb-finemapping-pip/input$ head GR018.txt                              CHR     BP      rsID    MAF     EA      NEA  BETA       SE      P       Zscore
1       762320  exm2268640              C    T  -2.1671804559878427     2.2192489884814903      0.3288  -0.9765377689642318
1       865584  exm44           G       A    -0.7989522394569218        0.9458814406017895      0.3983  -0.844664251947487
1       865625  exm46           G       A    -1.723727058836228 1.3810903732349589      0.212   -1.2480914299610266
1       865628  exm47           A       G    -3.798694320121143 11.010921607693835      0.7301  -0.34499331259127497
1       865662  exm51           G       A    -1.6841614586300369        1.0159911755963904      0.09739 -1.657653628380609
1       865665  exm53           G       A    -2.0091694886945044        2.640410901770726       0.4467  -0.7609306139991715
1       865694  exm55           C       T    -1.0624732420522365        0.4776340446018991      0.02612 -2.2244504010131694
1       866438  exm63           G       A    -0.8360941898798784        1.1243371703006841      0.4571  -0.7436329705761482
1       874501  exm94           C       T    -2.6664285264113907        8.142085007626491       0.7433  -0.32748718834473145

Do you know what can be going wrong? Thanks a lot!!

**Comment by ZJ-zuojing** [comment]
Hello silvenchu，
I also have the same question,Did you solve it?
@silvenchu thank you !

**Comment by xiechengyong123** [comment]
Me too!
@silvenchu thank you !

**Comment by Jianhua-Wang** [comment]
hey guys, I found this pipeline is less portable. Now I am working on a new pipeline along with some new features, such as custom LD reference panel and block window size. Please wait patiently.

**Comment by silvenchu** [comment]
Hello @xiechengyong123 !

We were able to run the code after making some changes. The path were some files were stored was wrong and that's why they couldn't be found. I am attaching our modified code:

[fine_map_pipe_natalia.pdf](https://github.com/mulinlab/CAUSALdb-finemapping-pip/files/9121885/fine_map_pipe_natalia.pdf)

**Comment by xiechengyong123** [comment]
silvenchu
Hello! I have received your email.
I admire your spirit of selfless code sharing.
Feel free to contact and communicate with me if you have any questions, good luck!


2022-7-18
| |
谢成勇
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 7/15/2022 23:02 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [mulinlab/CAUSALdb-finemapping-pip] File Not Found error: File (...) /.causal.txt' does not exist" (Issue #9) |

Hello @xiechengyong123 !

We were able to run the code after making some changes. The path were some files were stored was wrong and that's why they couldn't be found. I am attaching our modified code:

fine_map_pipe_natalia.pdf

**Comment by silvenchu** [comment]
@xiechengyong123 Sure! :) Credits go to my colleague Natalia Llonga, she modified the code and it worked, hope you managed to make it work too! 


> silvenchu Hello! I have received your email. I admire your spirit of selfless code sharing. Feel free to contact and communicate with me if you have any questions, good luck! 2022-7-18 | | 谢成勇 | | ***@***.*** | ---- Replied Message ---- | From | ***@***.***> | | Date | 7/15/2022 23:02 | | To | ***@***.***> | | Cc | ***@***.***> , ***@***.***> | | Subject | Re: [mulinlab/CAUSALdb-finemapping-pip] File Not Found error: File (...) /.causal.txt' does not exist" (Issue #9) | Hello @xiechengyong123 ! We were able to run the code after making some changes. The path were some files were stored was wrong and that's why they couldn't be found. I am attaching our modified code: fine_map_pipe_natalia.pdf — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by liggettla** [comment]
The modifications made by @silvenchu work for me on a local machine but not on a cluster environment and I'm getting the following Traceback. Is there a remaining directory somewhere that still needs to be changed?

Traceback (most recent call last):
  File "fine_map_pipe.py", line 286, in <module>
    get_credible_set(prefix)
  File "fine_map_pipe.py", line 130, in get_credible_set
    df = pd.read_csv(f'{out_dir}/{meta_id}_{chr_id}_{start}_{stop}.causal.txt',sep='\t',names=names)
  File "/opt/conda/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/opt/conda/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/opt/conda/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/opt/conda/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/opt/conda/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/opt/conda/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/opt/conda/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/mydir/CAUSALdb/GR018/GR018_1_54226262_56413117.causal.txt'

**Comment by liggettla** [comment]
I went through the code, and it looks like when `rsID` is left as `NA` or anything repetitive, all data will be dropped, producing the missing `*causal.txt` error. Instead of removing duplicates within the rsID column, duplicates can be removed on the `'CHR','BP','EA','NEA'` columns, and allows everything to run even with an absent `rsID`.

The following changes to the code should work:
```
54     # processed['rsID'] = processed['ID'] # makes rsID column all the same data
55     # processed = processed.drop_duplicates('rsID') # if rsID is blank, all data is removed
56     processed = processed.drop_duplicates(['CHR','BP','EA','NEA']) # instead drop on location
```

**Comment by shudanhua** [comment]
> I went through the code, and it looks like when `rsID` is left as `NA` or anything repetitive, all data will be dropped, producing the missing `*causal.txt` error. Instead of removing duplicates within the rsID column, duplicates can be removed on the `'CHR','BP','EA','NEA'` columns, and allows everything to run even with an absent `rsID`.
> 
> The following changes to the code should work:
> 
> ```
> 54     # processed['rsID'] = processed['ID'] # makes rsID column all the same data
> 55     # processed = processed.drop_duplicates('rsID') # if rsID is blank, all data is removed
> 56     processed = processed.drop_duplicates(['CHR','BP','EA','NEA']) # instead drop on location
> ```

Thank you so much! It worked!

**Comment by yunaibiao** [comment]
> Hello @xiechengyong123 ! 你好 ！
> 
> We were able to run the code after making some changes. The path were some files were stored was wrong and that's why they couldn't be found. I am attaching our modified code:进行一些更改后，我们能够运行代码。有些文件存储的路径错误，导致找不到。我附上我们修改后的代码：
> 
> [fine_map_pipe_natalia.pdf](https://github.com/mulinlab/CAUSALdb-finemapping-pip/files/9121885/fine_map_pipe_natalia.pdf)

hello,Could you provide the .py file?
